## NumPy

**`NumPy`** es una librería utilizada para el manejo de arreglos (arrays) y matrices multidimensionales, cuenta con múltiples funciones para trabajar con estos objetos. Una matriz en **`NumPy`** es una cuadricula de valores, todos del mismo tipo e indexados.

```python
import numpy as np
```

In [1]:
import numpy as np

In [2]:
lista = [1, 2, 3]

In [3]:
type(lista)

list

In [4]:
# Usando np.array() podemos castear una lista a un objeto numpy.ndarray
type(np.array(lista))

numpy.ndarray

### Arreglos (arrays) de 1 dimensión (vector).

| Método           | Atributo   |
|------------------|------------|
|**`.argmin()`**   |**`.dtype`**|
|**`.argmax()`**   |**`.ndim`** |
|**`.cumsum()`**   |**`.size`** |
|**`.cumprod()`**  |**`.shape`**|
|**`.dot()`**      | **`.T`**   |
|**`.flatten()`**  |            |
|**`.max()`**      |            |
|**`.min()`**      |            |
|**`.mean()`**     |            |
|**`.reshape()`**  |            |
|**`.transpose()`**|            |
|**`.sum()`**      |            |
|**`.sort()`**     |            |
|**`.tolist()`**   |            |

In [9]:
vector = [-2, 4, 1, 3.5,200, 7, 8, -4]

vector = np.array(vector)

vector

array([ -2. ,   4. ,   1. ,   3.5, 200. ,   7. ,   8. ,  -4. ])

In [10]:
# .argmin() y .argmax() retornan el indice del minimo y del maximo respectivamente
print(vector.argmin())
print(vector.argmax())

7
4


In [12]:
vector[4]

200.0

In [17]:
lista2 = ['pepes', 'juanes', 'luna', 'enrique']
lista2_array = np.array(lista2)

In [18]:
print(lista2_array.argmin())
print(lista2_array.argmax())

3
0


In [13]:
# .cumsum() y cumprod() retorna un np.array() con la suma acumulada y el producto acumulado respectivamente

print(vector.cumsum())
print(vector.cumprod())

[ -2.    2.    3.    6.5 206.5 213.5 221.5 217.5]
[-2.0000e+00 -8.0000e+00 -8.0000e+00 -2.8000e+01 -5.6000e+03 -3.9200e+04
 -3.1360e+05  1.2544e+06]


In [30]:
# .reshape() cambia la "forma" de la matriz

matriz_1 = vector.reshape(4, 2)

matriz_1

array([[ -2. ,   4. ],
       [  1. ,   3.5],
       [200. ,   7. ],
       [  8. ,  -4. ]])

In [31]:
# .transpose() hace la transpuesta de la matriz, también se puede usar .

print(matriz_1.transpose())

print("-"*20)

print(matriz_1.T)

[[ -2.    1.  200.    8. ]
 [  4.    3.5   7.   -4. ]]
--------------------
[[ -2.    1.  200.    8. ]
 [  4.    3.5   7.   -4. ]]


In [34]:
# .tolist() retorna el array en una lista

type(matriz_1.tolist()[1])

list

In [35]:
type(list(matriz_1)[0])

numpy.ndarray

In [36]:
vector

array([ -2. ,   4. ,   1. ,   3.5, 200. ,   7. ,   8. ,  -4. ])

In [37]:
matriz_1

array([[ -2. ,   4. ],
       [  1. ,   3.5],
       [200. ,   7. ],
       [  8. ,  -4. ]])

In [38]:
# .flatten() retorna un vector plano con los elementos de la matriz

matriz_1.flatten()

array([ -2. ,   4. ,   1. ,   3.5, 200. ,   7. ,   8. ,  -4. ])

In [39]:
# .sort() ordena la matriz de menor a mayor, lo hace in-place

print("Antes de .sort()", vector)

vector.sort()

print("Después de .sort()", vector)

Antes de .sort() [ -2.    4.    1.    3.5 200.    7.    8.   -4. ]
Después de .sort() [ -4.   -2.    1.    3.5   4.    7.    8.  200. ]


In [40]:
vector

array([ -4. ,  -2. ,   1. ,   3.5,   4. ,   7. ,   8. , 200. ])

In [41]:
# .ndim retorna el número de dimensiones

vector.ndim

1

In [42]:
# .size retorna el número de elementos

vector.size

8

In [43]:
# .shape retorna en una tupla las dimesiones de la matriz

vector.shape

(8,)

In [44]:
matriz_1.shape

(4, 2)

In [45]:
# .dtype retorna el tipo de dato de los elementos de la matriz

vector.dtype

dtype('float64')

### Arreglos (arrays) de 2 dimensiones (matrices).

Comparte los métodos y atributos de los vectores por que son de la misma clase.

Existen varias funciones para inicializar matrices o arrays:

| Función                  | Descripción                                                                             |
|--------------------------|-----------------------------------------------------------------------------------------|
|**`np.empty((n, m))`**    | Inicializa una matriz **nxm** vacia.                                                    |
|**`np.zeros((n, m))`**    | Inicializa una matriz **nxm** de ceros.                                                 |
|**`np.ones((n, m))`**     | Inicializa una matriz **nxm** de unos.                                                  |
|**`np.eye(n)`**           | Inicializa la matriz identidad de orden **n**.                                          |
|**`np.identity(n)`**      | Inicializa la matriz identidad de orden **n**.                                          |
|**`np.full(shape, elem)`**| Inicializa una matriz con la forma de **`shape`** usando los elementos de **`elem`**.   |
|**`np.linspace(a, b, p)`**| Inicializa un array de **`p`** elementos entre **`a`** y **`b`**, todos **x-distantes**.|

In [48]:
matriz = np.array([[1, 2, 3, 10], 
                   [4, 5, 6, 20], 
                   [7, 8, 9, 30]])

matriz

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20],
       [ 7,  8,  9, 30]])

In [49]:
print(matriz)

[[ 1  2  3 10]
 [ 4  5  6 20]
 [ 7  8  9 30]]


In [50]:
matriz.flatten()

array([ 1,  2,  3, 10,  4,  5,  6, 20,  7,  8,  9, 30])

In [51]:
matriz.reshape(6, 2)

array([[ 1,  2],
       [ 3, 10],
       [ 4,  5],
       [ 6, 20],
       [ 7,  8],
       [ 9, 30]])

In [52]:
# Aunque muestre numeros dentro de la matriz, np.empty() la inicializa vacia, estos números que se ven
# Estan en memoria y numpy los usa para mostrar la matriz

empty = np.empty(shape = (5, 5), dtype = "float")

print(empty)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.78020984e-306
  7.56587584e-307]
 [1.37961302e-306 1.05699242e-307 8.01097889e-307 1.78020169e-306
  7.56601165e-307]
 [1.02359984e-306 1.24610383e-306 9.34603679e-307 8.34423068e-308
  8.06610070e-308]
 [8.34424342e-308 1.02360256e-306 1.86921143e-306 8.06640627e-308
  8.01106038e-307]
 [6.89805151e-307 1.78020169e-306 1.42410974e-306 1.69105613e-306
  2.22809558e-312]]


In [53]:
# Inicializa una matriz de 1's.

ones = np.ones(shape = (5, 5), dtype = "int8")

print(ones)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [54]:
# Inicializa una matriz de 0's.

zeros = np.zeros(shape = (5, 5), dtype = "int8")

print(zeros)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [55]:
# Matriz identidad

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
# np.full() crea una lista con forma "shape" y la llena con un iterable.

full = np.full(shape = (5, 5), fill_value = range(5))

print(full)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [58]:
full = np.full(shape = (5, 5), fill_value = [False if i%2!=0 else True for i in range(5)])

print(full)

[[ True False  True False  True]
 [ True False  True False  True]
 [ True False  True False  True]
 [ True False  True False  True]
 [ True False  True False  True]]


In [62]:
# np.linspace(a, b, p) crea un array de "p" elementos entre "a" y "b", todos x-distantes

linspace = np.linspace(-15, 15, 40)

print(linspace)

[-15.         -14.23076923 -13.46153846 -12.69230769 -11.92307692
 -11.15384615 -10.38461538  -9.61538462  -8.84615385  -8.07692308
  -7.30769231  -6.53846154  -5.76923077  -5.          -4.23076923
  -3.46153846  -2.69230769  -1.92307692  -1.15384615  -0.38461538
   0.38461538   1.15384615   1.92307692   2.69230769   3.46153846
   4.23076923   5.           5.76923077   6.53846154   7.30769231
   8.07692308   8.84615385   9.61538462  10.38461538  11.15384615
  11.92307692  12.69230769  13.46153846  14.23076923  15.        ]


### Slicing en NumPy

En Python para hacer slicing de una lista de listas debiamos escribir primero la "fila" y de segundo la "columna" asi:
```python
lista[a][b]
```

Usando un **`np.array()`** podemos usar la siguiente notación:
```python
array[a, b]
```

Incluso, podemos pasar un **slicing** dentro del **slicing** para filtrar aun más los datos:
```python
array[a1 : a2, b1 : b2]
```

También podemos hacer **indexing** dentro del **slicing**

```python
array[[a1, a3], [b2, b4]]
```

In [63]:
matriz = np.array([[1, 0, 0, 0, 0], [0, 0, 2, 0, 0], [1, 1, 0, 0, 1], [2, 1, 1, 1, 0], [1, 2, 1, 2, 2]])

print(matriz)

[[1 0 0 0 0]
 [0 0 2 0 0]
 [1 1 0 0 1]
 [2 1 1 1 0]
 [1 2 1 2 2]]


In [64]:
# Hacer

matriz[4][1]

2

In [65]:
# Es igual que hacer

matriz[4, 1]

2

In [68]:
# Slicing
matriz[1:4, 1:4] # primer elemento son las filas a mostrar y el segundo las columnas

array([[0, 2, 0],
       [1, 0, 0],
       [1, 1, 1]])

In [67]:
# Slicing + Indexing

matriz[[1, 3], [2, 4]]

array([2, 0])

### Operaciones con Arrays

In [69]:
A = np.array([[20, 40], [30, 50]])
B = np.array([[4, 5], [2, 3]])

print(A)
print("-"*20)
print(B)

[[20 40]
 [30 50]]
--------------------
[[4 5]
 [2 3]]


In [70]:
# Suma

A + B

array([[24, 45],
       [32, 53]])

In [71]:
# Resta
A - B

array([[16, 35],
       [28, 47]])

In [72]:
# Multiplicación por escalar

A * 5

array([[100, 200],
       [150, 250]])

In [73]:
# Multiplicación elemento a elemento (no es la forma matemática de multiplicar)

A * B

array([[ 80, 200],
       [ 60, 150]])

In [74]:
# División por escalar

A / 5

array([[ 4.,  8.],
       [ 6., 10.]])

In [75]:
# Producto de matrices (también conocido como producto de vectorial)

A.dot(B)

array([[160, 220],
       [220, 300]])

In [76]:
print(A)
print("-"*20)
print(B)

[[20 40]
 [30 50]]
--------------------
[[4 5]
 [2 3]]


#### Concatenar

In [77]:
# Concatenar verticalmente

np.concatenate((A, B), axis = 0)

array([[20, 40],
       [30, 50],
       [ 4,  5],
       [ 2,  3]])

In [78]:
# Concatenar horizontalmente

np.concatenate((A, B), axis = 1)

array([[20, 40,  4,  5],
       [30, 50,  2,  3]])

### Números aleatorios en NumPy

|Función                             |Descripción                                                                                                                                         |
|------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------|
|**`np.random.random(n)`**           | Genera un número aleatorio entre 0 y 1, si damos el parametro **`n`** genera una lista de **`n`** elementos aleatorios entre 0 y 1, solo genera vectores.                                                                                                                       |
|**`np.random.rand(shape)`**         | Genera un array de forma **shape** con números aleatorios entre 0 y 1.                                                                             |
|**`np.random.randn(shape)`**        | Genera un array de forma **shape** con números aleatorios entre -1 y 1.                                                                           |
|**`no.random.randint(a, b, size)`** | Genera un array de tamaño **size** con numeros enteros aleatorios entre **a** y **b**.                                                             |
|**`np.random.choice(obj, size, p)`**| Genera un array de tamaño **size** con los elementos de **obj**, se le pueden dar pesos a los elementos usando **p**, retorna elementos repetidos.|
|**`np.random.seed(n)`**             | Genera una semilla.                                                                                                                                 |
|**`np.random.RandomState(n)`**      | Genera una semilla.                                                                                                                                 |

In [81]:
np.random.random(size = (5, 5))

array([[0.80930351, 0.63465694, 0.7716001 , 0.8040517 , 0.50584522],
       [0.00488644, 0.04220911, 0.89221259, 0.85345471, 0.75623072],
       [0.35280088, 0.25832448, 0.08272748, 0.53035647, 0.71884576],
       [0.1176431 , 0.56043276, 0.93195073, 0.62868998, 0.57310584],
       [0.16856914, 0.58262693, 0.39156783, 0.8601479 , 0.20163392]])

In [82]:
print(np.random.random())

print("-"*30)

print(np.random.random(5))

0.3687893612027845
------------------------------
[0.69048724 0.3742721  0.55162329 0.36144855 0.1796216 ]


In [83]:
print(np.random.rand())

print("-"*30)

print(np.random.rand(2, 3))

0.8579938212833352
------------------------------
[[0.43007857 0.30594251 0.71837516]
 [0.87199695 0.36448582 0.72728712]]


In [87]:
print(np.random.rand())

print("-"*30)

print(np.random.rand(3, 3, 3))

0.5519016773514258
------------------------------
[[[0.19853413 0.25831288 0.99417185]
  [0.3718475  0.92303419 0.40125354]
  [0.55777725 0.99731249 0.2703969 ]]

 [[0.803802   0.61564012 0.32686267]
  [0.30493823 0.23106893 0.77656201]
  [0.64708433 0.21336873 0.58488991]]

 [[0.91900562 0.39765009 0.17660306]
  [0.66890759 0.04089637 0.02016965]
  [0.54566    0.82712099 0.81997238]]]


In [88]:
print(np.random.randn())

print("-"*30)

print(np.random.randn(2, 3))

0.24347795497853006
------------------------------
[[-0.27685774 -2.29658112 -0.90719938]
 [ 0.08373064  0.08416151 -0.55363561]]


In [89]:
print(np.random.randint(0, 10))

print("-"*30)

print(np.random.randint(1, 10, size = [5, 5]))

5
------------------------------
[[6 2 8 2 4]
 [8 9 1 6 9]
 [1 1 2 9 3]
 [8 1 7 1 3]
 [1 6 1 5 2]]


In [90]:
print(np.random.choice(["a", "e", "i", "o", "u"], size = 10, p = [0.6, 0.1, 0.1, 0.1, 0.1])) 

['u' 'a' 'o' 'a' 'a' 'a' 'a' 'o' 'a' 'a']


In [91]:
print(np.random.choice(["a", "e", "i", "o", "u"], size = 10)) 

['o' 'o' 'a' 'u' 'u' 'u' 'u' 'e' 'i' 'i']


In [93]:
for i in range(10):
    np.random.seed(4)
    print(np.random.randn())

0.05056170714293955
0.05056170714293955
0.05056170714293955
0.05056170714293955
0.05056170714293955
0.05056170714293955
0.05056170714293955
0.05056170714293955
0.05056170714293955
0.05056170714293955


In [94]:
for i in range(4):
    rs = np.random.RandomState(2)
    print(rs.rand())
    print(rs.randint(0, 10))
    print(np.random.randn()) # No usa rs
    print("-"*30)   

0.43599490214200376
8
0.499951333237829
------------------------------
0.43599490214200376
8
-0.9959089311068651
------------------------------
0.43599490214200376
8
0.6935985082913116
------------------------------
0.43599490214200376
8
-0.41830152002691007
------------------------------


In [102]:
seed1 = np.random.RandomState(15)

for i in range(4):
    print(seed1.rand())
    print(seed1.randint(0, 10))
    print(seed1.randn())
    print("-"*30)

0.8488176972685787
5
-0.15590853388271336
------------------------------
0.27540092860641197
5
-0.5017896732977485
------------------------------
0.02495303232907431
1
-0.9021190404034566
------------------------------
0.8724294447722278
4
0.6891445632908499
------------------------------


In [109]:
# Código para establecer el número de decimales (Cambiar {0:0.2f} para elegir el número de decimales)

np.set_printoptions(formatter = {"float" : lambda x: "{0:0.4f}".format(x)})

np.random.randn(6, 6)

array([[-0.3186, -1.1808, -1.1728, -0.0523, -0.8462, 1.4145],
       [0.3359, -1.1129, 0.5131, -0.2283, 0.2338, 1.5416],
       [0.9187, -0.9136, 0.5024, -0.4281, 1.0230, -0.0322],
       [-1.5943, -3.4663, -0.6779, -0.8283, -0.7891, 2.1736],
       [0.1169, 0.8692, -0.9520, 0.6558, -0.5540, -1.5716],
       [-0.3249, -0.0543, -1.0856, 1.4299, 0.0507, -1.5465]])

In [ ]:
np.random.randn(6, 6)

In [110]:
np.empty((5, 5), dtype = "float64")

array([[0.8093, 0.6347, 0.7716, 0.8041, 0.5058],
       [0.0049, 0.0422, 0.8922, 0.8535, 0.7562],
       [0.3528, 0.2583, 0.0827, 0.5304, 0.7188],
       [0.1176, 0.5604, 0.9320, 0.6287, 0.5731],
       [0.1686, 0.5826, 0.3916, 0.8601, 0.2016]])

In [ ]:
################################################################################################################################